# Generated by Django 3.2.4 on 2023-07-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=128)),
                ('date_joined', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
